# Generated by Django 4.2.11 on 2024-05-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaine', models.CharField(default='', max_length=64)),
                ('superviseur', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(default='', max_length=64)),
                ('status', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(default='', max_length=64)),
                ('kitting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kitting')),
                ('projet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Bon_de_sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='En préparation', max_length=64)),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.poste')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projet')),
            ],
        ),
    ]
