# Generated by Django 4.2.11 on 2024-05-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bon_de_sortie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='En préparation', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Kitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaine', models.CharField(default='', max_length=64)),
                ('superviseur', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(default='', max_length=64)),
                ('status', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(default='', max_length=64)),
                ('kitting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.kitting')),
                ('projet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_intern', models.CharField(max_length=64)),
                ('ref_fourn', models.CharField(default='', max_length=64)),
                ('designation', models.CharField(default='', max_length=64)),
                ('fournisseur', models.CharField(default='', max_length=64)),
                ('qte_en_stk', models.FloatField()),
                ('qte_a_sortir', models.FloatField()),
                ('status', models.CharField(default='', max_length=64)),
                ('bon_de_sortie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bon_de_sortie')),
            ],
        ),
        migrations.AddField(
            model_name='bon_de_sortie',
            name='poste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.poste'),
        ),
        migrations.AddField(
            model_name='bon_de_sortie',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projet'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_intern', models.CharField(max_length=64)),
                ('ref_fourn', models.CharField(default='', max_length=64)),
                ('designation', models.CharField(default='', max_length=64)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Art_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('ref_intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.article')),
            ],
        ),
    ]
