# Generated by Django 4.2.11 on 2024-05-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_intern', models.CharField(max_length=64)),
                ('ref_fourn', models.CharField(default='', max_length=64)),
                ('designation', models.CharField(default='', max_length=64)),
                ('fournisseur', models.CharField(default='', max_length=64)),
                ('qte_en_stk', models.FloatField()),
                ('qte_a_sortir', models.FloatField()),
                ('status', models.CharField(default='', max_length=64)),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.poste')),
                ('projet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_intern', models.CharField(max_length=64)),
                ('ref_fourn', models.CharField(default='', max_length=64)),
                ('designation', models.CharField(default='', max_length=64)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Art_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('ref_intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.article')),
            ],
        ),
    ]
