# Generated by Django 4.2.11 on 2024-05-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_listing_bon_de_sortie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=64)),
                ('selected_poste_id', models.IntegerField()),
            ],
        ),
    ]
