# Generated by Django 4.2.11 on 2024-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_state_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bon_de_sortie_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
